/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectmanagementsoftware.gui;

import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import projectmanagementsoftware.Project;
import projectmanagementsoftware.linkedlist.LinkedListNode;

/**
 *
 * @author david
 */
public class BOMPanel extends javax.swing.JPanel {
    private Project project;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form WBSAnimationPanel
     */
    public BOMPanel(Project project) {
        initComponents();
        
        this.project = project;
        this.tableModel = new DefaultTableModel();
        this.tableModel.addColumn("Entregable");
        this.tableModel.addColumn("Costo");
        this.tableModel.addColumn("Total Acumulado");
        this.bomTable.setModel(this.tableModel);
        this.reload();
    }

    public Project getProject() {
        return project;
    }

    
    public void reload() {
        DecimalFormat format = new DecimalFormat("$###,###.###");
        this.titleLabel.setText("Presupuesto " + this.project.getName());
        LinkedListNode<Double> total = new LinkedListNode<>(0.0);
        
        this.project.getWbs().getDeliverables().forEach(deliverable -> {
            total.set(total.get() + deliverable.getCost());
            
            this.tableModel.addRow(new Object[] {
                deliverable.getName(),
                format.format(deliverable.getCost()),
                format.format(total.get())
            });
        });
        
        this.totalLabel.setText(format.format(total.get()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        mainContentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bomTable = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1026, 603));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setPreferredSize(new java.awt.Dimension(1026, 603));

        mainContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Presupuesto");
        mainContentPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        bomTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Entregable", "Costo", "Total Acumulado"
            }
        ));
        jScrollPane1.setViewportView(bomTable);

        mainContentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 760, 380));

        totalLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        totalLabel.setText("Total: ");
        mainContentPanel.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 360, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Total: ");
        mainContentPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 60, -1));

        scrollPane.setViewportView(mainContentPanel);

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bomTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
