/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectmanagementsoftware.gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import projectmanagementsoftware.linkedlist.LinkedList;
import projectmanagementsoftware.Project;
import projectmanagementsoftware.linkedlist.LinkedListNode;
import projectmanagementsoftware.wbs.Deliverable;
import projectmanagementsoftware.wbs.WBSNode;
import projectmanagementsoftware.wbs.WorkPackage;

/**
 *
 * @author david
 */
public class GUI extends javax.swing.JFrame {
    private LinkedList<Project> projects;
    private DefaultListModel<String> memberListModel;
    private DefaultTreeModel treeModel;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        this.projects = Project.load();
        this.memberListModel = new DefaultListModel<>();
        this.projectMembersList.setModel(this.memberListModel);
        this.mainContentTabPane.removeAll();
        this.treeModel = new DefaultTreeModel(new DefaultMutableTreeNode(new WorkPackage("Proyectos")));
        this.wbsTree.setModel(this.treeModel);
        this.wbsTree.setRootVisible(false);
        this.wbsTree.setCellRenderer(new WBSTreeCellRenderer());
        this.updateUI();
    }

    public void updateUI() {
        DefaultMutableTreeNode treeRoot = (DefaultMutableTreeNode) this.treeModel.getRoot();
        treeRoot.removeAllChildren();
        
        this.projects.forEach(project -> {
            treeRoot.add(project.getWbs().toJTree());
        });
        
        this.treeModel.reload();
        
        for (int i = 0; i < this.wbsTree.getRowCount(); i++) {
            this.wbsTree.expandRow(i);
        }
    }
    
    public void showCreateProjectDialog() {
        this.projectNameField.setText("");
        this.addMemberField.setText("");
        this.memberListModel.clear();
        this.newProjectDialog.setLocationRelativeTo(this);
        this.newProjectDialog.setVisible(true);
    }
    
    public void showAddWorkPackageDialog() {
        WorkPackage parent = (WorkPackage) this.getSelectedWorkPackage();
        
        if (parent == null)
            return;
        
        this.workPackageParentField.setText(parent.getPath());
        this.workPackageNameField.setText("");
        this.newWorkPackageDialog.setLocationRelativeTo(this);
        this.newWorkPackageDialog.setVisible(true);
    }
    
    public void showAddDeliverableDialog() {
        WorkPackage parent = (WorkPackage) this.getSelectedWorkPackage();
        
        if (parent == null)
            return;
        
        this.deliverableParentField.setText(parent.getPath());
        this.deliverableNameField.setText("");
        this.deliverableDescriptionArea.setText("");
        this.newDeliverableDialog.setLocationRelativeTo(this);
        this.newDeliverableDialog.setVisible(true);
    }
    
    public WorkPackage getSelectedWorkPackage() {
        WBSNode node = this.getSelectedNode();
        
        if (node instanceof Deliverable) {
            showError("El nodo padre debe ser un paquete de trabajo");
            return null;
        }
        
        return (WorkPackage) node;
    }
    
    public WBSNode getSelectedNode() {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) this.wbsTree.getLastSelectedPathComponent();
        
        if (node == null) {
            showError("No se ha seleccionado un paquete de trabajo o proyecto");
            return null;
        }
            
        return (WBSNode) node.getUserObject();
    }
    
    public void showError(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newProjectDialog = new javax.swing.JDialog();
        addMemberField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        projectMembersList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        projectNameField = new javax.swing.JTextField();
        addMemberButton = new javax.swing.JButton();
        cancelNewProjectButton = new javax.swing.JButton();
        confirmNewProjectButton = new javax.swing.JButton();
        removeMemberButton = new javax.swing.JButton();
        newWorkPackageDialog = new javax.swing.JDialog();
        workPackageParentField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        workPackageNameField = new javax.swing.JTextField();
        cancelNewWorkPackageButton = new javax.swing.JButton();
        confirmNewWorkPackageButton = new javax.swing.JButton();
        newDeliverableDialog = new javax.swing.JDialog();
        deliverableParentField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deliverableNameField = new javax.swing.JTextField();
        cancelNewDeliverableButton = new javax.swing.JButton();
        confirmNewDeliverableButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        deliverableDescriptionArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        newProjectButton = new javax.swing.JButton();
        wbsButton = new javax.swing.JButton();
        scheduleButton = new javax.swing.JButton();
        addWorkPackage = new javax.swing.JButton();
        addDeliverable = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        fileExplorerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wbsTree = new javax.swing.JTree();
        idkPanel = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        mainContentTabPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        newProjectDialog.setTitle("Nuevo Proyecto");
        newProjectDialog.setAlwaysOnTop(true);
        newProjectDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newProjectDialog.setMaximumSize(new java.awt.Dimension(365, 364));
        newProjectDialog.setMinimumSize(new java.awt.Dimension(365, 364));
        newProjectDialog.setModal(true);
        newProjectDialog.setPreferredSize(new java.awt.Dimension(365, 364));
        newProjectDialog.setResizable(false);
        newProjectDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addMemberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberFieldActionPerformed(evt);
            }
        });
        newProjectDialog.getContentPane().add(addMemberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 180, 30));

        jLabel1.setText("Integrantes");
        newProjectDialog.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jScrollPane3.setViewportView(projectMembersList);

        newProjectDialog.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 260, 120));

        jLabel2.setText("Nombre del proyecto");
        newProjectDialog.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        newProjectDialog.getContentPane().add(projectNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 260, 30));

        addMemberButton.setText("+");
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });
        newProjectDialog.getContentPane().add(addMemberButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 40, 30));

        cancelNewProjectButton.setText("Cancelar");
        cancelNewProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewProjectButtonActionPerformed(evt);
            }
        });
        newProjectDialog.getContentPane().add(cancelNewProjectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 120, 40));

        confirmNewProjectButton.setText("Confirmar");
        confirmNewProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewProjectButtonActionPerformed(evt);
            }
        });
        newProjectDialog.getContentPane().add(confirmNewProjectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 40));

        removeMemberButton.setText("-");
        removeMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMemberButtonActionPerformed(evt);
            }
        });
        newProjectDialog.getContentPane().add(removeMemberButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 40, 30));

        newWorkPackageDialog.setTitle("Nuevo Paquete de Trabajo");
        newWorkPackageDialog.setAlwaysOnTop(true);
        newWorkPackageDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newWorkPackageDialog.setMaximumSize(new java.awt.Dimension(365, 236));
        newWorkPackageDialog.setMinimumSize(new java.awt.Dimension(365, 236));
        newWorkPackageDialog.setModal(true);
        newWorkPackageDialog.setPreferredSize(new java.awt.Dimension(365, 236));
        newWorkPackageDialog.setResizable(false);
        newWorkPackageDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workPackageParentField.setEditable(false);
        workPackageParentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workPackageParentFieldActionPerformed(evt);
            }
        });
        newWorkPackageDialog.getContentPane().add(workPackageParentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 260, 30));

        jLabel3.setText("Padre");
        newWorkPackageDialog.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setText("Nombre de paquete de trabajo");
        newWorkPackageDialog.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        newWorkPackageDialog.getContentPane().add(workPackageNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 260, 30));

        cancelNewWorkPackageButton.setText("Cancelar");
        cancelNewWorkPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewWorkPackageButtonActionPerformed(evt);
            }
        });
        newWorkPackageDialog.getContentPane().add(cancelNewWorkPackageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, 40));

        confirmNewWorkPackageButton.setText("Confirmar");
        confirmNewWorkPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewWorkPackageButtonActionPerformed(evt);
            }
        });
        newWorkPackageDialog.getContentPane().add(confirmNewWorkPackageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, 40));

        newDeliverableDialog.setTitle("Nuevo Entregable");
        newDeliverableDialog.setAlwaysOnTop(true);
        newDeliverableDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newDeliverableDialog.setLocationByPlatform(true);
        newDeliverableDialog.setMaximumSize(new java.awt.Dimension(365, 414));
        newDeliverableDialog.setMinimumSize(new java.awt.Dimension(365, 390));
        newDeliverableDialog.setModal(true);
        newDeliverableDialog.setPreferredSize(new java.awt.Dimension(365, 414));
        newDeliverableDialog.setResizable(false);
        newDeliverableDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliverableParentField.setEditable(false);
        deliverableParentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverableParentFieldActionPerformed(evt);
            }
        });
        newDeliverableDialog.getContentPane().add(deliverableParentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 260, 30));

        jLabel5.setText("Descripción");
        newDeliverableDialog.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setText("Nombre del Entregable");
        newDeliverableDialog.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        newDeliverableDialog.getContentPane().add(deliverableNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 260, 30));

        cancelNewDeliverableButton.setText("Cancelar");
        cancelNewDeliverableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewDeliverableButtonActionPerformed(evt);
            }
        });
        newDeliverableDialog.getContentPane().add(cancelNewDeliverableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 120, 40));

        confirmNewDeliverableButton.setText("Confirmar");
        confirmNewDeliverableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewDeliverableButtonActionPerformed(evt);
            }
        });
        newDeliverableDialog.getContentPane().add(confirmNewDeliverableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 120, 40));

        deliverableDescriptionArea.setColumns(20);
        deliverableDescriptionArea.setRows(5);
        jScrollPane5.setViewportView(deliverableDescriptionArea);

        newDeliverableDialog.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, 130));

        jLabel8.setText("Padre");
        newDeliverableDialog.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        header.setPreferredSize(new java.awt.Dimension(1280, 80));
        header.setLayout(new javax.swing.BoxLayout(header, javax.swing.BoxLayout.LINE_AXIS));

        newProjectButton.setText("Nuevo Proyecto");
        newProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectButtonActionPerformed(evt);
            }
        });
        header.add(newProjectButton);

        wbsButton.setText("EDT");
        header.add(wbsButton);

        scheduleButton.setText("Cronograma");
        header.add(scheduleButton);

        addWorkPackage.setText("Nuevo Paquete de trabajo");
        addWorkPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWorkPackageActionPerformed(evt);
            }
        });
        header.add(addWorkPackage);

        addDeliverable.setText("Nuevo Entregable");
        addDeliverable.setToolTipText("");
        addDeliverable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeliverableActionPerformed(evt);
            }
        });
        header.add(addDeliverable);

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        panel1.setLayout(new javax.swing.BoxLayout(panel1, javax.swing.BoxLayout.LINE_AXIS));

        sidebar.setMaximumSize(new java.awt.Dimension(250, 640));
        sidebar.setMinimumSize(new java.awt.Dimension(200, 0));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 640));
        sidebar.setLayout(new javax.swing.BoxLayout(sidebar, javax.swing.BoxLayout.Y_AXIS));

        fileExplorerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fileExplorerPanel.setLayout(new javax.swing.BoxLayout(fileExplorerPanel, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(250, 316));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Proyectos");
        wbsTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        wbsTree.setPreferredSize(new java.awt.Dimension(250, 316));
        jScrollPane2.setViewportView(wbsTree);

        fileExplorerPanel.add(jScrollPane2);

        sidebar.add(fileExplorerPanel);

        idkPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout idkPanelLayout = new javax.swing.GroupLayout(idkPanel);
        idkPanel.setLayout(idkPanelLayout);
        idkPanelLayout.setHorizontalGroup(
            idkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        idkPanelLayout.setVerticalGroup(
            idkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        sidebar.add(idkPanel);

        panel1.add(sidebar);

        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        mainContentTabPane.addTab("tab1", jScrollPane1);

        panel2.add(mainContentTabPane, java.awt.BorderLayout.CENTER);

        panel1.add(panel2);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectButtonActionPerformed
        //String projectName = JOptionPane.showInputDialog(this, "Nombre del proyecto", "Nuevo proyecto", JOptionPane.QUESTION_MESSAGE);
        //projects.add(new Project(projectName));
        this.showCreateProjectDialog();
    }//GEN-LAST:event_newProjectButtonActionPerformed

    private void addMemberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMemberFieldActionPerformed

    private void confirmNewProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewProjectButtonActionPerformed
        String projectName = this.projectNameField.getText();
        
        final LinkedListNode<Boolean> sw = new LinkedListNode<>(false);
        
        this.projects.forEach(project -> {
            if (project.getName().equals(projectName)) {
                sw.set(true);
            }
        });
        
        if (sw.get()) {
            showError("Ya existe un proyecto con ese nombre");
            return;
        }
        
        LinkedList<String> team = new LinkedList<>();
        
        for (Object member : this.memberListModel.toArray()) {
            team.add((String) member);
        }
        
        this.projects.add(Project.create(projectName, team));
        this.newProjectDialog.setVisible(false);
        this.updateUI();
    }//GEN-LAST:event_confirmNewProjectButtonActionPerformed

    private void cancelNewProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewProjectButtonActionPerformed
        this.newProjectDialog.setVisible(false);
    }//GEN-LAST:event_cancelNewProjectButtonActionPerformed

    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed
        String newMember = this.addMemberField.getText();
        
        if (newMember.equals("")) {
            showError("No se ha ingresado un nombre");
            return;
        }
        
        this.memberListModel.addElement(newMember);
        this.addMemberField.setText("");
    }//GEN-LAST:event_addMemberButtonActionPerformed

    private void removeMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMemberButtonActionPerformed
        for (String member : this.projectMembersList.getSelectedValuesList()) {
            this.memberListModel.removeElement(member);
        }
    }//GEN-LAST:event_removeMemberButtonActionPerformed

    private void addWorkPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWorkPackageActionPerformed
        this.showAddWorkPackageDialog();
    }//GEN-LAST:event_addWorkPackageActionPerformed

    private void workPackageParentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workPackageParentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workPackageParentFieldActionPerformed

    private void cancelNewWorkPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewWorkPackageButtonActionPerformed
        this.newWorkPackageDialog.setVisible(false);
    }//GEN-LAST:event_cancelNewWorkPackageButtonActionPerformed

    private void confirmNewWorkPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewWorkPackageButtonActionPerformed
        String name = this.workPackageNameField.getText();
        String parentPath = this.workPackageParentField.getText();
        String projectName = parentPath.split("/")[0];

        projects.forEach(project -> {
            if (project.getName().equals(projectName)) {
                project.getWbs().add(WorkPackage.create(name, parentPath + "/" + name));
            }
        });

        this.newWorkPackageDialog.setVisible(false);
        this.updateUI();
    }//GEN-LAST:event_confirmNewWorkPackageButtonActionPerformed

    private void deliverableParentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverableParentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliverableParentFieldActionPerformed

    private void cancelNewDeliverableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewDeliverableButtonActionPerformed
        this.newDeliverableDialog.setVisible(false);
    }//GEN-LAST:event_cancelNewDeliverableButtonActionPerformed

    private void confirmNewDeliverableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewDeliverableButtonActionPerformed
        String name = this.deliverableNameField.getText();
        String description = this.deliverableDescriptionArea.getText();
        String parentPath = this.deliverableParentField.getText();
        String projectName = parentPath.split("/")[0];

        projects.forEach(project -> {
            if (project.getName().equals(projectName)) {
                project.getWbs().add(Deliverable.create(name, parentPath + "/" + name + ".txt", description));
            }
        });

        this.newDeliverableDialog.setVisible(false);
        this.updateUI();
    }//GEN-LAST:event_confirmNewDeliverableButtonActionPerformed

    private void addDeliverableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeliverableActionPerformed
        this.showAddDeliverableDialog();
    }//GEN-LAST:event_addDeliverableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeliverable;
    private javax.swing.JButton addMemberButton;
    private javax.swing.JTextField addMemberField;
    private javax.swing.JButton addWorkPackage;
    private javax.swing.JButton cancelNewDeliverableButton;
    private javax.swing.JButton cancelNewProjectButton;
    private javax.swing.JButton cancelNewWorkPackageButton;
    private javax.swing.JButton confirmNewDeliverableButton;
    private javax.swing.JButton confirmNewProjectButton;
    private javax.swing.JButton confirmNewWorkPackageButton;
    private javax.swing.JTextArea deliverableDescriptionArea;
    private javax.swing.JTextField deliverableNameField;
    private javax.swing.JTextField deliverableParentField;
    private javax.swing.JPanel fileExplorerPanel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel idkPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane mainContentTabPane;
    private javax.swing.JDialog newDeliverableDialog;
    private javax.swing.JButton newProjectButton;
    private javax.swing.JDialog newProjectDialog;
    private javax.swing.JDialog newWorkPackageDialog;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JList<String> projectMembersList;
    private javax.swing.JTextField projectNameField;
    private javax.swing.JButton removeMemberButton;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton wbsButton;
    private javax.swing.JTree wbsTree;
    private javax.swing.JTextField workPackageNameField;
    private javax.swing.JTextField workPackageParentField;
    // End of variables declaration//GEN-END:variables
}
