/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectmanagementsoftware.gui;

import projectmanagementsoftware.Project;

/**
 *
 * @author david
 */
public class SchedulePanel extends javax.swing.JPanel {
    private Project project;
    
    /**
     * Creates new form WBSAnimationPanel
     */
    public SchedulePanel(Project project) {
        initComponents();
        
        this.project = project;
    }

    public Project getProject() {
        return project;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        animationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1026, 603));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane.setPreferredSize(new java.awt.Dimension(1026, 603));

        animationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/fish.png"))); // NOI18N
        jLabel1.setText("Aquí se mostraría el cronograma si estuviera implementado");
        animationPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -100, 880, 750));

        scrollPane.setViewportView(animationPanel);

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
